//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHN_Humber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentRequest
    {
        public int Id { get; set; }
        public string PatientName { get; set; }
        public Nullable<int> PatientAge { get; set; }
        public string PatientSex { get; set; }
        public string PatientPhone { get; set; }
        public string PatientEmail { get; set; }
        public Nullable<System.DateTime> PreferredDate { get; set; }
        public string Reasons { get; set; }
    }
}
