//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHN_Humber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int DocId { get; set; }
        public string Doc_academic_affiliation { get; set; }
        public string Doc_clinic { get; set; }
        public string Doc_education_and_training { get; set; }
        public string Doc_email { get; set; }
        public string Doc_first_name { get; set; }
        public string Doc_image { get; set; }
        public string Doc_languages { get; set; }
        public string Doc_last_name { get; set; }
        public string Doc_middle_name { get; set; }
        public string Doc_phone { get; set; }
        public string Doc_program { get; set; }
        public string Doc_publications { get; set; }
        public string Doc_research_institute_affiliations { get; set; }
        public string Doc_research_profile { get; set; }
        public string Doc_specialty { get; set; }
    }
}
