//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHN_Humber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int DonationId { get; set; }
        public string DonationName { get; set; }
        public Nullable<System.DateTime> DonationDate { get; set; }
        public Nullable<int> DonationAmount { get; set; }
        public string DonationRecipient { get; set; }
        public string DonationPhone { get; set; }
        public string DonationEmail { get; set; }
        public string DonationAddress { get; set; }
        public string DonationCreditCard { get; set; }
    }
}
