//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHN_Humber.Models
{


    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Event
    {

        public int EventID { get; set; }

        [Required(ErrorMessage = "Please Enter the Event Title")]
        public string EventTitle { get; set; }

        [Required(ErrorMessage = "Please Select the Event Date")]
        public Nullable<System.DateTime> EventDate { get; set; }

        public string EventTime { get; set; }


        [Required(ErrorMessage = "Please Enter the Event Location")]
        public string EventLocation { get; set; }

        public string EventDescription { get; set; }

        public string EventRecurred { get; set; }

    }
}
