//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHN_Humber.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class faq_question
    {
        public int faq_question_id { get; set; }
        [Required(ErrorMessage = "Please enter the question")]
        public string faq_question_question { get; set; }
        [Required(ErrorMessage = "Please enter the answer")]
        public string faq_question_answer { get; set; }
        public Nullable<int> faq_question_category { get; set; }
        public Nullable<int> faq_question_order { get; set; }
    }
}
