//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHN_Humber.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class faq_category
    {
        public int faq_category_id { get; set; }

        [Required(ErrorMessage = "Please enter the category name")]
        public string faq_category_name { get; set; }
        public Nullable<int> faq_category_order { get; set; }
    }
}
