//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHN_Humber.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FAQCategory
    {
        public int FAQCategoryID { get; set; }
        [Required(ErrorMessage ="Please enter the category name")]
        public string FAQCategoryName { get; set; }
        public Nullable<int> FAQCategoryOrder { get; set; }
    }
}
