//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHN_Humber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQQuestion
    {
        public int FAQQuestionID { get; set; }
        public string FAQQuestionQuestion { get; set; }
        public string FAQQuestionAnswer { get; set; }
        public Nullable<int> FAQQuestionCategory { get; set; }
        public Nullable<int> FAQQuestionOrder { get; set; }
    }
}
