//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHN_Humber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntellisenceSetting
    {
        public int id { get; set; }
        public byte Intellisense { get; set; }
        public int Result_limit { get; set; }
        public int Debounce_Time { get; set; }
    }
}
