//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHN_Humber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuGroup
    {
        public int MenuGroupId { get; set; }
        public string MenuGroupName { get; set; }
        public string MenuGroupItem { get; set; }
    }
}
