//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHN_Humber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int EmployeeId { get; set; }
        public string AdminName { get; set; }
        public string NewsNumber { get; set; }
        public string NewsTitle { get; set; }
        public string NewsContent { get; set; }
    }
}
