//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHN_Humber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoTable
    {
        public string AdminName { get; set; }
        public string EmployeeId { get; set; }
        public string VideoNumber { get; set; }
        public string VideoLink { get; set; }
    }
}
